### ISSUE TITLE
issue triggering joingame when pressing claim on the widget

### ISSUE THREAD

**Issue by pseudozach** [pseudozach/lnswap-widget#5]
widget is called with these parameters 
`triggerTrustlessRewards 420400000 Stx with preimage 8cc8d328a560bbf9d684876b5dac6991f4c991618b8f86a6128d594059a7c2be and timelock 60352 for nft ST38F25DF7V9VN1TP2Y9QP7A1KB4AF7PK8CHV4QF7 trustless-rewards and call to ST38F25DF7V9VN1TP2Y9QP7A1KB4AF7PK8CHV4QF7.trustless-rewards`

on claim it gives below error:
>Uncaught (in promise) TypeError: Invalid value type. Must be a number, bigint, integer-string, hex-string, BN.js instance, or Buffer.
    at intToBigInt (utils.js:252:11)
    at uintCV (intCV.js:23:86)
    at _callee5$ (Widget.js:1225:286)
    at tryCatch (runtime.js:63:40)
    at Generator.invoke [as _invoke] (runtime.js:294:22)
    at Generator.eval [as next] (runtime.js:119:21)
    at asyncGeneratorStep (Widget.js:51:103)
    at _next (Widget.js:53:194)
    at eval (Widget.js:53:364)
    at new Promise (<anonymous>)
    at Widget.eval [as triggerTrustlessRewards] (Widget.js:53:97)
    at _callee$ (Widget.js:272:21)
    at tryCatch (runtime.js:63:40)
    at Generator.invoke [as _invoke] (runtime.js:294:22)
    at Generator.eval [as next] (runtime.js:119:21)
    at asyncGeneratorStep (Widget.js:51:103)
    at _next (Widget.js:53:194)
    at eval (Widget.js:53:364)
    at new Promise (<anonymous>)
    at eval (Widget.js:53:97)
    at HTMLUnknownElement.callCallback (react-dom.development.js:362:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:411:16)
    at invokeGuardedCallback (react-dom.development.js:466:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:480:25)
    at executeDispatch (react-dom.development.js:612:3)
    at executeDispatchesInOrder (react-dom.development.js:637:5)
    at executeDispatchesAndRelease (react-dom.development.js:743:5)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:752:10)
    at forEachAccumulated (react-dom.development.js:724:8)
    at runEventsInBatch (react-dom.development.js:769:3)
    at runExtractedPluginEventsInBatch (react-dom.development.js:914:3)
    at handleTopLevel (react-dom.development.js:5848:5)
    at batchedEventUpdates$1 (react-dom.development.js:24343:12)
    at batchedEventUpdates (react-dom.development.js:1463:12)
    at dispatchEventForPluginEventSystem (react-dom.development.js:5943:5)
    at attemptToDispatchEvent (react-dom.development.js:6059:5)
    at dispatchEvent (react-dom.development.js:5963:19)
    at unstable_runWithPriority (scheduler.development.js:815:12)
    at runWithPriority$2 (react-dom.development.js:12188:10)
    at discreteUpdates$1 (react-dom.development.js:24359:12)
    at discreteUpdates (react-dom.development.js:1486:12)
    at dispatchDiscreteEvent (react-dom.development.js:5926:3)

**Comment by pseudozach** [comment]
confirmed this was due to missing input parameter. 

Probably can use some improvement on parameter checking to avoid failures but this should really be responsibility of the integrating app to ensure params are passed correctly.
